/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomInput: typeof import('./src/components/BottomInput.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./src/components/Header.vue')['default']
    IconCopy: typeof import('./src/components/Icons/IconCopy.vue')['default']
    IconEdit: typeof import('./src/components/Icons/IconEdit.vue')['default']
    IntroSelf: typeof import('./src/components/IntroSelf.vue')['default']
    MainDialogue: typeof import('./src/components/MainDialogue.vue')['default']
  }
}
